### ISSUE TITLE
Ticket Creation Fails to Save name and email Field in Unified SDK

### ISSUE THREAD

**Issue by jo-2031** [unified-to/unified-python-sdk#2]
The Unified SDK’s ticketing API is not saving the name field. Despite providing the correct data, the response shows an empty name field and no emails, although the telephone number is saved correctly. Example response:
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/50a45f00-d3a2-438c-972d-8982625f5ed9">

{"id":"4772478622","name":"","emails":[],"telephones":[{"telephone":"1234567890"}],"created_at":"2024-08-12T09:55:44.000Z","updated_at":"2024-08-12T09:55:44.000Z"}

Please investigate the issue and provide guidance on resolving it.

**Comment by Neel-Dandiwala** [comment]
Hi @jo-2031, is the issue still persisting?

**Comment by Neel-Dandiwala** [comment]
As I haven't received a response, I will assume the problem is solved. Please let us know if it still persist!
